# Generated by Django 6.0.6 on 2026-06-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('fk_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.people')),
            ],
        ),
        migrations.CreateModel(
            name='Archdiocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('fk_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church')),
                ('fk_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.people')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.people')),
            ],
        ),
    ]
